seed: 1
record_video: true
device: "cuda"

environment:
  step_size: 0.001
  rtf: 1.0
  steps_per_run: 1

  render: True
  num_envs: 5
  num_threads: 40
  seed: 1
  simulation_dt: 0.004
  control_dt: 0.024
  max_time: 6.0
  torqueRewardCoeff: -2e-5

  architecture:
    policy: [256, 128]
    value_net: [256, 128]
    init_scale: 0.1
    activation: "Tanh"

  algorithm:
    minibatch: 2
    epoch: 4
    gamma: 0.99
    lambda: 0.95
    entropy_coeff: 0.0
    learning_rate: 5e-4
    clip_param: 0.2
    curriculum_param: 0.998
    intial_factor: 0.001