[build-system]
build-backend = "setuptools.build_meta"
requires = [
    "setuptools>=45",
    "setuptools_scm[toml]>=6.0",
    "cmake-build-extension",
    "wheel",
    "idyntree",
]

[tool.setuptools_scm]
root = ".."
relative_to = "__file__"
local_scheme = "dirty-tag"
